In [4]:
import numpy as np

a = np.array([1,2,3])

print(a)

element = a[1]

print(element)

[1 2 3]
2


In [8]:
#tạo mảng 2 chiều

matrix = np.array([[1,3,4],[23,42,2],[2,7,8]])
element = matrix[1,2]
print(matrix,element)


[[ 1  3  4]
 [23 42  2]
 [ 2  7  8]] 2


In [14]:
a = np.empty(5)
print(a)

#tao mang tu 1 -> 100
a = np.arange(100)
print(a)





[6.23042070e-307 4.67296746e-307 1.69121096e-306 8.69412980e-312
 2.52560479e-317]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


In [42]:
#them xoa xua sap xep mang

arr = np.array([2,3,5,7,1])
print(arr)

arr = np.sort(arr)
print("Sap xep:",arr)

arr = np.sort(arr)[::-1]
print("Nguoc:",arr)

arr = np.append(arr,100)
print("Them:",arr)

arr = np.delete(arr,3)
print("Xoa",arr)

arr = np.array([[3,1,2],[5,2,2],[7,5,8]])
sortcol = np.sort(arr,axis=1)
print("sort col:",sortcol)
sortrow = np.sort(arr,axis=0)
print("sort row:",sortrow)
print("số chiều:",arr.ndim)
print("kích thước:",arr.size)
print("Hình dạng:",arr.shape)

#chuyể kiểu dữ liệu
arr = np.array([3,5,575,2,321,1,4235,7,232])
print("Chuyển kiểu:",arr.astype(float))


[2 3 5 7 1]
Sap xep: [1 2 3 5 7]
Nguoc: [7 5 3 2 1]
Them: [  7   5   3   2   1 100]
Xoa [  7   5   3   1 100]
sort col: [[1 2 3]
 [2 2 5]
 [5 7 8]]
sort row: [[3 1 2]
 [5 2 2]
 [7 5 8]]
số chiều: 2
kích thước: 9
Hình dạng: (3, 3)
Chuyển kiểu: [3.000e+00 5.000e+00 5.750e+02 2.000e+00 3.210e+02 1.000e+00 4.235e+03
 7.000e+00 2.320e+02]


In [56]:
#thay đổi hình dạng
arr = np.array([3,5,575,2,321,1])
print(arr)
reshape = arr.reshape(2,3)
print(reshape)

print("Chuyển thành mảng 1 chiều",arr.flatten())

[  3   5 575   2 321   1]
[[  3   5 575]
 [  2 321   1]]
Chuyển thành mảng 1 chiều [  3   5 575   2 321   1]


In [54]:
#chuyển vị mảng
arr = np.array([[1,2,3],[4,5,6]])
print(arr.T)

arr1= np.array([1,3,4])
arr2= np.array([2,6,8])
arr = np.concatenate(arr1,arr2)
print(arr)


[[1 4]
 [2 5]
 [3 6]]


TypeError: only integer scalar arrays can be converted to a scalar index